stages:
  - test
  - docker
  - helm

helm-lint:
  stage: test
  image: registry.gitlab.com/xdev-tech/build/helm:3.0
  script:
    - helm dependency update ./helm/keycloak
    - lint keycloak helm/keycloak --values helm/keycloak/values-dev.yaml

publish_docker:
  stage: docker
  image:
    name: registry.gitlab.com/xdev-tech/build/docker:3.0
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - build_with_helm_tag $CI_REGISTRY_IMAGE helm/keycloak

publish_helm_oci:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:3.0
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm dependency update ./helm/keycloak
    - build $CI_REGISTRY_IMAGE/helm/keycloak ./helm/keycloak

publish_helm:
  stage: helm
  image: registry.gitlab.com/xdev-tech/build/helm:3.0
  script:
    - helm registry login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - helm dependency update ./helm/keycloak
    - build_std ./helm/keycloak
