stages:
  - prepare
  - publish
  - test

ci:
  stage: prepare
  image:
    name: tbxdev/build-docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildctl-daemonless.sh build
      --frontend dockerfile.v0
      --local context=ci
      --local dockerfile=ci
      --export-cache mode=max,type=registry,ref=$CI_REGISTRY_IMAGE/ci:buildcache,push=true
      --import-cache type=registry,ref=$CI_REGISTRY_IMAGE/ci:buildcache
      --output type=image,name=$CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG,push=true
  only:
    changes:
      - ci/*

docker-image:
  stage: publish
  image:
    name: tbxdev/build-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildctl-daemonless.sh build
      --frontend dockerfile.v0
      --local context=.
      --local dockerfile=.
      --secret id=gitlabToken,env=CI_JOB_TOKEN
      --export-cache mode=max,type=registry,ref=$CI_REGISTRY_IMAGE/keycloak:buildcache,push=true
      --import-cache type=registry,ref=$CI_REGISTRY_IMAGE/keycloak:buildcache
      --output type=image,name=$CI_REGISTRY_IMAGE/keycloak:$CI_COMMIT_REF_SLUG,push=true

k8s:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
  script:
    - k3d cluster create default --port 80:80@loadbalancer --port 443:443@loadbalancer
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - kubectl create secret docker-registry gitlab-registry
      --docker-server=$CI_REGISTRY
      --docker-username=$CI_REGISTRY_USER
      --docker-password=$CI_REGISTRY_PASSWORD
    - helm install kc bitnami/keycloak
      --set image.registry=$CI_REGISTRY
      --set image.repository=$CI_PROJECT_PATH/keycloak
      --set image.tag=$CI_COMMIT_REF_SLUG
      --set image.pullSecrets={gitlab-registry}
      --timeout 10m
      --wait || (kubectl describe pod && false)
    - helm list
