## String to partially override aspnet-core.fullname template (will maintain the release name)
nameOverride: ""

## String to fully override aspnet-core.fullname template
fullnameOverride: ""

## The number of keycloak nodes to run. Use this number instead of scaling the stateful set after
## the installation, because so resources (swarm services mostly) are only scaled with this value
replicas: 1

## keycloak image configuration
image:
  repository: registry.gitlab.com/xdev-tech/xdev-enterprise-business-network/keycloak
  pullPolicy: IfNotPresent
  # tag: 17.0:0

adminUser: kcadmin
# adminPassword:

## keycloak service configuration
service:
  type: ClusterIP
  port: 8080
  ipAddress: null

## keycloak container resources
resources:
  # limits: {}
  requests:
    memory: 400Mi
    cpu: 100m

## Affinity for keycloak pods assignment
affinity: {}

# Tolerations for keycloak pods assignment
tolerations: {}

## Service account for keycloak to use.
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Add networkpolicies
networkPolicy:
  enabled: true

## Ingress configuration
ingress:
  # activate keycloack ingress
  enabled: false
  # host name to use for all the ingresses
  # host:
  annotations:
    kubernetes.io/tls-acme: "true"
  # tls secret name for all the ingresses
  # secretName:
  from:
    - podSelector: {}
      namespaceSelector:
        matchLabels:
          name: ingress

# the configurator is backed by terraform with a keycloak provider
configurator:
  # variables to pass to the configurator as environment variables
  # the key is prefixed with TF_VAR_ in order to be understood as
  # a var value by terraform
  secrets: {}
    # realm_id: foo

  # some files to add to the terraform configuration
  # a default configuration is available in default.tf and may be
  # overriden here
  files: {}
    # default.tf: ""


## activate metric collection through prometheus ServiceMonitor resources
metrics:
  enabled: false
  interval:
  scrapeTimeout:

db:
  nameOverride: keycloak-db
  auth:
    existingSecret: "{{ .Release.Name }}-{{ .Values.nameOverride }}"
    username: keycloak
    database: keycloak
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: 50Mi
      cpu: 50m
  primary:
    service:
      ports:
        postgresql: 5432
    annotations:
      reloader.stakater.com/auto: "true"
  rbac:
    create: true
  serviceAccount:
    create: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
  networkPolicy:
    enabled: true
    ingressRules:
      primaryAccessOnlyFrom:
        enabled: true
        podSelector:
          '{{ template "common.names.fullname" . }}-client': "true"
