ingress:
  host: "kc.localhost"
  enabled: true
replicas: 1
metrics:
  enabled: true
global:
  dev: true
configurator:
  secrets:
    realm_id: foo
    array:
      - foo
      - bar
    map:
      foo: bar
  files:
    client.tf: |-
      resource "keycloak_openid_client" "openid_client" {
        realm_id            = keycloak_realm.main.id
        client_id           = "backend"
        access_type         = "CONFIDENTIAL"
      }
