keycloak:
  service:
    type: NodePort
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  image:
    registry: registry.gitlab.com
    repository: the-blockchain-xdev/xdev-product/enterprise-business-network/keycloak/keycloak
    tag: develop
    pullSecrets:
      - gitlab-registry
  auth:
    adminUser: kcadmin
    adminPassword: kcadmin
