ingress:
  host: "kc.localhost"
  enabled: true
replicas: 1
metrics:
  enabled: true
global:
  dev: true
configurator:
  variables:
    realm_id: foo
    array:
      - foo
      - bar
    map:
      foo: bar
  secrets:
    backend_secret: e3a54938-29e7-4660-9838-76b576dd41d2
  files:
    client.tf: |-
      resource "keycloak_openid_client" "backend" {
        realm_id            = keycloak_realm.main.id
        client_id           = "backend"
        access_type         = "CONFIDENTIAL"
        client_secret       = var.backend_secret
      }
      variable "backend_secret" {
        type      = string
        sensitive = true
      }
