apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-configurator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  {{- range $k, $v := .Values.configurator.files }}
  {{ $k | quote }}: |-
    {{- $v | nindent 4 }}
  {{- end }}
