{{- if (default .Values.ingress.enabled .Values.ingress.enabled) -}}
{{- $fullName := printf "%s" (include "keycloak.fullname" .) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with (default .Values.ingress.annotations .Values.ingress.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | required "please provide a hostname for the ingress" | quote }}
      secretName: {{ tpl (.Values.ingress.secretName | default (printf "%s-tls" $fullName)) $ }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end -}}
