{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  podSelector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ include "keycloak.fullname" . }}-client: "true"
        # allow communication between the pods of this chart, when replicas is greater than 1
        - podSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: keycloak
        {{- .Values.ingress.from | toYaml | nindent 8 }}
{{- end }}
