{{ $name := printf "%s-configurator" (include "keycloak.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.configurator.secrets }}
  {{- if or (kindIs "map" $v) (kindIs "slice" $v) }}
  TF_VAR_{{ $k }}: {{ $v | toJson | b64enc }}
  {{- else }}
  TF_VAR_{{ $k }}: {{ $v | b64enc }}
  {{- end }}
  {{- end }}
