{{ $name := (include "keycloak.db.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "keycloak.automaticSecret" (list . $name "password" 20 .Values.db.auth.password) | indent 2 }}
{{- include "keycloak.automaticSecret" (list . $name "postgres-password" 20 .Values.db.auth.postgresPassword) | indent 2 }}
