{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
      targetPort: http
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}
