apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: http
  clusterIP: None
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
